name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [readme-dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      # Create a new branch and switch to it
      - name: Create New Branch
        run: |
          git checkout -b github-3D-contrib
          git push --set-upstream origin github-3D-contrib

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      # Commit and Push on the new branch
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push github-3D-contrib
