name: Generate Github Json Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Github Stats Json Style
        uses: ridemountainpig/github-stats-json-style@v1.0.0
        with:
          username: ridemountainpig
          push-branch: main
